// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forge/v1/agent.proto

package forgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteAgentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Prompt           string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ConfigJson       string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,3,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	BlueprintName    string                 `protobuf:"bytes,4,opt,name=blueprint_name,json=blueprintName,proto3" json:"blueprint_name,omitempty"`
	NodeId           string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RunId            string                 `protobuf:"bytes,6,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteAgentRequest) Reset() {
	*x = ExecuteAgentRequest{}
	mi := &file_forge_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAgentRequest) ProtoMessage() {}

func (x *ExecuteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAgentRequest.ProtoReflect.Descriptor instead.
func (*ExecuteAgentRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteAgentRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecuteAgentRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *ExecuteAgentRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ExecuteAgentRequest) GetBlueprintName() string {
	if x != nil {
		return x.BlueprintName
	}
	return ""
}

func (x *ExecuteAgentRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteAgentRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ExecuteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteAgentResponse) Reset() {
	*x = ExecuteAgentResponse{}
	mi := &file_forge_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAgentResponse) ProtoMessage() {}

func (x *ExecuteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAgentResponse.ProtoReflect.Descriptor instead.
func (*ExecuteAgentResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteAgentResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteAgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_forge_v1_agent_proto protoreflect.FileDescriptor

const file_forge_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14forge/v1/agent.proto\x12\bforge.v1\"\xd2\x01\n" +
	"\x13ExecuteAgentRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\x12+\n" +
	"\x11working_directory\x18\x03 \x01(\tR\x10workingDirectory\x12%\n" +
	"\x0eblueprint_name\x18\x04 \x01(\tR\rblueprintName\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06run_id\x18\x06 \x01(\tR\x05runId\"^\n" +
	"\x14ExecuteAgentResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2[\n" +
	"\n" +
	"ForgeAgent\x12M\n" +
	"\fExecuteAgent\x12\x1d.forge.v1.ExecuteAgentRequest\x1a\x1e.forge.v1.ExecuteAgentResponseB8Z6github.com/aditya-soni/forge/internal/grpcexec/forgev1b\x06proto3"

var (
	file_forge_v1_agent_proto_rawDescOnce sync.Once
	file_forge_v1_agent_proto_rawDescData []byte
)

func file_forge_v1_agent_proto_rawDescGZIP() []byte {
	file_forge_v1_agent_proto_rawDescOnce.Do(func() {
		file_forge_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forge_v1_agent_proto_rawDesc), len(file_forge_v1_agent_proto_rawDesc)))
	})
	return file_forge_v1_agent_proto_rawDescData
}

var file_forge_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forge_v1_agent_proto_goTypes = []any{
	(*ExecuteAgentRequest)(nil),  // 0: forge.v1.ExecuteAgentRequest
	(*ExecuteAgentResponse)(nil), // 1: forge.v1.ExecuteAgentResponse
}
var file_forge_v1_agent_proto_depIdxs = []int32{
	0, // 0: forge.v1.ForgeAgent.ExecuteAgent:input_type -> forge.v1.ExecuteAgentRequest
	1, // 1: forge.v1.ForgeAgent.ExecuteAgent:output_type -> forge.v1.ExecuteAgentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forge_v1_agent_proto_init() }
func file_forge_v1_agent_proto_init() {
	if File_forge_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forge_v1_agent_proto_rawDesc), len(file_forge_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forge_v1_agent_proto_goTypes,
		DependencyIndexes: file_forge_v1_agent_proto_depIdxs,
		MessageInfos:      file_forge_v1_agent_proto_msgTypes,
	}.Build()
	File_forge_v1_agent_proto = out.File
	file_forge_v1_agent_proto_goTypes = nil
	file_forge_v1_agent_proto_depIdxs = nil
}
