// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: forge/v1/agent.proto

package forgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForgeAgent_ExecuteAgent_FullMethodName = "/forge.v1.ForgeAgent/ExecuteAgent"
)

// ForgeAgentClient is the client API for ForgeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForgeAgentClient interface {
	ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (*ExecuteAgentResponse, error)
}

type forgeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewForgeAgentClient(cc grpc.ClientConnInterface) ForgeAgentClient {
	return &forgeAgentClient{cc}
}

func (c *forgeAgentClient) ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (*ExecuteAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteAgentResponse)
	err := c.cc.Invoke(ctx, ForgeAgent_ExecuteAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForgeAgentServer is the server API for ForgeAgent service.
// All implementations must embed UnimplementedForgeAgentServer
// for forward compatibility.
type ForgeAgentServer interface {
	ExecuteAgent(context.Context, *ExecuteAgentRequest) (*ExecuteAgentResponse, error)
	mustEmbedUnimplementedForgeAgentServer()
}

// UnimplementedForgeAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForgeAgentServer struct{}

func (UnimplementedForgeAgentServer) ExecuteAgent(context.Context, *ExecuteAgentRequest) (*ExecuteAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAgent not implemented")
}
func (UnimplementedForgeAgentServer) mustEmbedUnimplementedForgeAgentServer() {}
func (UnimplementedForgeAgentServer) testEmbeddedByValue()                    {}

// UnsafeForgeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForgeAgentServer will
// result in compilation errors.
type UnsafeForgeAgentServer interface {
	mustEmbedUnimplementedForgeAgentServer()
}

func RegisterForgeAgentServer(s grpc.ServiceRegistrar, srv ForgeAgentServer) {
	// If the following call panics, it indicates UnimplementedForgeAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForgeAgent_ServiceDesc, srv)
}

func _ForgeAgent_ExecuteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeAgentServer).ExecuteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeAgent_ExecuteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeAgentServer).ExecuteAgent(ctx, req.(*ExecuteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForgeAgent_ServiceDesc is the grpc.ServiceDesc for ForgeAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForgeAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forge.v1.ForgeAgent",
	HandlerType: (*ForgeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteAgent",
			Handler:    _ForgeAgent_ExecuteAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forge/v1/agent.proto",
}
